In [6]:
from pytrends.request import TrendReq
import pandas as pd

pytrends = TrendReq(hl='en-US', tz=360)

In [9]:
pd.DataFrame(pytrends.suggestions("Trường Đại học Công nghệ thông tin"))

,mid,title,type
0,/m/02qqlmm,University of Information Technology - VNUHCM,"University in Ho Chi Minh City, Vietnam"
1,/g/1yjg80dyy,Vietnam - Korea University of Information and ...,"College in Da Nang, Vietnam"
2,/g/1tczbc88,"Faculty of Information Technology, Hanoi Open ...","Academic department in Hanoi, Vietnam"
3,/g/11c561sgsg,Faculty of Information Technology & Communicat...,"College in Can Tho, Vietnam"
4,/g/11fvrzhdg5,"Khoa Công Nghệ Thông Tin, Trường Đại học Sư ph...","Academic department in Ho Chi Minh City, Vietnam"

In [ ]:
kw_list = ["/m/03ytc"]
pytrends.build_payload(kw_list, timeframe='today 5-y', geo='VI')
pytrends.interest_over_time()

# Các định dạng timeframe
# Mặc định: 'today 5-y' (5 năm gần nhất)
# Toàn bộ: 'all'
# Ngày cụ thể: '2016-12-14 2017-01-25'
# Ngày giờ cụ thể (theo UTC): '2017-02-06T10 2017-02-12T07'
# Theo tháng: 'today 3-m' (chỉ hỗ trợ 1, 3, 12 tháng)
# Theo ngày: 'now 7-d' (chỉ hỗ trợ 1, 7 ngày)
# Theo giờ: 'now 1-H' (chỉ hỗ trợ 1, 4 giờ)

            /m/03ytc  isPartial
date
2021-10-03         0      False
2021-10-10         0      False
2021-10-17         0      False
2021-10-24         0      False
2021-10-31         0      False
...              ...        ...
2026-09-06         0      False
2026-09-13         0      False
2026-09-20         0      False
2026-09-27         0      False
2026-10-04         0       True

[262 rows x 2 columns]

In [ ]:
import requests, json

url = "https://trends.google.com/trends/api/autocomplete/iron"
r = requests.get(url, params={"hl": "en-US"})

# Google thêm tiền tố chống XSSI ")]}'," ở đầu, cần cắt bỏ
data = json.loads(r.text[5:])
print(data["default"]["topics"])